### ISSUE TITLE
SDWebImage - What's your name

### ISSUE THREAD

**Issue by bpoplauschi** [rs/SDWebImage#2291]
Per #2285, review all the entity names before releasing 5.0.0-beta.

- [ ] stop using `SDWebImage` as a default prefix for entities. `SD` is our official prefix. `Web` means the entity applies only to web resources. `Image` refers only to images.

Proposals:
- [x] rename `SDWebImageCachesManager*` to `SDImageCachesManager*` #2292 
- [x] rename `SDWebImageCache*` to `SDImageCache*` #2292 
- [x] rename `NSImage (Additions)` to `NSImage (Compatibility)` #2293 
- [x] rename `SDWebImageTransformer*` to `SDImageTransformer*` #2304 
- [x] rename `SDWebImageCacheKeyFilter` to `SDCacheKeyFilter`
- [x] rename `SDWebImageProgressiveDownload` to `SDWebImageProgressiveLoad` #2294
- [x] rename `SDWebImageFrame` to `SDImageFrame` #2305
- [x] rename `SDWebImageCoderHelper` to `SDImageCoderHelper` #2305
- [x] rename `SDWebImage*Coder` to `SDImage*Coder` #2306
  + `SDWebImageCoder` protocol -> `SDImageCoder`
  + `SDWebImageProgressiveCoder` protocol -> `SDProgressiveImageCoder`
  + `SDWebImageAnimatedCoder` protocol -> `SDAnimatedImageCoder`
  + `SDWebImageCodersManager` -> `SDImageCodersManager`
  + `SDWebImageImageIOCoder` -> `SDImageIOCoder`
  + `SDWebImageGIFCoder` -> `SDImageGIFCoder`
  + `SDWebImageWebPCoder` -> `SDImageWebPCoder`
  + `SDWebImageAPNGCoder` -> `SDImageAPNGCoder`
- [x] rename `SDWebImageLoader*` to `SDImageLoader*`

Top level API - to be discussed if we make those
- [ ] rename `SDWebImageManager*` to `SDImageManager*`
- [ ] rename `SDWebImageDownloader*` to `SDImageDownloader*`

CC @dreampiggy @skyline75489 @mythodeia 

![](https://user-images.githubusercontent.com/6919743/39305445-b61a51e8-498f-11e8-839e-971dac45112c.jpeg)

**Comment by dreampiggy** [comment]
Maybe some image decoding/encoding related class can also be renmaed. But I wonder does this changes's gain is much more than the gain ?

Anyway, here is the suggestion I think can be renamed without that `SDWebImage` prefix to simple `SDImage` prefix.

### Recommend to change (Not widely used by user in 4.x)
+ `SDWebImageCoderHelper` Class -> `SDImageCoderHelper` (Actualy this class is really independent, only include `SDWebImageCompat.h`, even without that `SDWebImageDefine`)
+ `SDWebImageFrame` Class -> `SDImageFrame` (Really independent too)

### Carefuly considered to change (May be widely used by user in 4.x), or maybe keep current naming.
+ `SDWebImageCoder` Protocol -> `SDImageCoder`
+ `SDWebImageProgressiveCoder` Protocol -> `SDProgressiveImageCoder`
+ `SDWebImageAnimatedCoder` Protocol -> `SDAnimatedImageCoder`
+ `SDWebImageImageIOCoder` Class -> `SDImageIOCoder`
+ `SDWebImageGIFCoder` -> `SDGIFCoder`
+ `SDWebImageWebPCoder` -> `SDWebPCoder`
+ `SDWebImageAPNGCoder` -> `SDAPNGCoder`

**Comment by dreampiggy** [comment]
I'm not recommend to change `SDWebImageManager` something. This class are all the really common Core API. Change this will cause 4.x user really hard to migration. And the naming it's good with `Web`.

Our framework is create aim to `Asynchronous image downloader with cache support as a UIImageView category`. And `SDWebImage` it's the framework's naming. It's no need to change.

I suggest to change something not really in common usage, and it's pure non-network, non-Photos and anything about `Loading` to without out that `SDWebImage` prefix.

For exmaple, `SDWebImageTransformer` is about `Loading`, because it's used by manager to transform downloaded image into another format. And cache also using this.

Only something like `SDWebImageCoderHelper`, which does not contains any business about `Loading`, can be renamed to `SDImageCoderHelper`

**Comment by bpoplauschi** [comment]
@dreampiggy I agree about people using `SDWebImageManager` along with the `UIView` extensions. But for 90% of our users, that should be it.
A 5.x major release allows us to change the interface and optimize it.

- one reason for those renaming is pure readability: shorter entity names are easier to read and the code does not extend that much
- another reason: we have the `SD` prefix for all the entities. That is sufficient to avoid name collisions. Now all the other parts of the name need to make sense:
  - `SDWebImageManager` is a manager that handles loading of images, not necessarily from the web. That is why the `web` word is confusing in it's name.
  - `SDWebImageTransformer` is an image transformer, its API just allows changing from an input image to an output image, there is no relation to the `web`
  - an even more interesting example: `SDWebImageCacheKeyFilter` has nothing to do with `web` or even `image`, it's just a cache key filter
  - same principle for the `context` names, we just don't need to carry over that redundant `WebImage`

**Comment by dreampiggy** [comment]
Some of changes actually are unnecessary, and more like a Philosophical problem.
The `SDWebImage` prefix not always means **This is a class about Web & Image, come on**. Some of class or headers is about **This is files using in `SDWebImage` framework, and represent the common thing used in framework.

For example, `SDWebImageContext` is created aim to `hold anything that `SDWebImageOptions` can not hold. This is because of lack of Objective-C enum. It does not means that `context` is for Web only. This two is about the `options` & `context` works hole through our Core API.

**Comment by bpoplauschi** [comment]
This was the logic we used for naming, but it's not ideal.
It's ok that we don't agree :) so we can have a constructive discussion and decide.

My 2 suggestions:
- let's look at other libraries as example. For instance [AFNetworking](https://github.com/AFNetworking/AFNetworking) which for me is a model for all Objective-C open source projects. They do not name their entities as `AFNetworking....`, but just use the `AF` prefix and then use the most relevant name for that component. Examples: `AFHTTPSessionManager`, `AFSecurityPolicy`, `AFURLRequestSerialization`
- extend the conversation to our colleagues @mythodeia @skyline75489 @rs what do you guys think?

**Comment by mythodeia** [comment]
@bpoplauschi i am too a fan of AFNetworking and indeed its a model open source project for all others. I agree with using the ```SD``` prefix instead of ```SDWebImage```.
I will say it again. Naming is hard and trying to find names that "work" well for both swift and obj-c is a bit hard.

**Comment by dreampiggy** [comment]
It seems that there are no pending issue about 5.x ? So maybe it's time to talk about this naming.

In recentlly write a keynote about the architecture of SDWebImage. So I'm now a little agree with the naming issue.

But to say, I'm not agreed to renaming more and more classes. I'will focus on the 5.x new features naming.

I'd suggest to renaming these class, which will cause much API break :

+ `SDWebImageTransformer` -> `SDImageTransformer`
+ `SDWebImageFrame` -> `SDImageFrame`
+ `SDWebImageCoderHelper` -> `SDImageCoderHelper`
+ `SDWebImageCoder` protocol -> `SDImageCoder`
+ `SDWebImageProgressiveCoder` protocol -> `SDProgressiveImageCoder`
+ `SDWebImageAnimatedCoder` protocol -> `SDAnimatedImageCoder`
+ `SDWebImageCodersManager` -> `SDImageCodersManager`
+ `SDWebImageImageIOCoder` -> `SDImageIOImageCoder`
+ `SDWebImageGIFCoder` -> `SDGIFImageCoder`
+ `SDWebImageWebPCoder` -> `SDWebPImageCoder`
+ `SDWebImageAPNGCoder` -> `SDAPNGImageCoder`

**Comment by dreampiggy** [comment]
![sdwebimage-5 x-architecture](https://user-images.githubusercontent.com/6919743/39304056-ef454a86-498a-11e8-8e3b-a7947de2643e.jpeg)

**Comment by dreampiggy** [comment]
![sdwebimage-5 x-architecture](https://user-images.githubusercontent.com/6919743/39305445-b61a51e8-498f-11e8-839e-971dac45112c.jpeg)

**Comment by bpoplauschi** [comment]
@dreampiggy yeap, we are closing in to the beta release. Just a few things we really need to do.

About naming, I think we can find some middle ground:
- go ahead with the strong renaming I proposed above
- to avoid breaking top level API, we can just keep some aliases around
```objective-c
@compatibility_alias SDWebImageManager SDImageManager;
```

Note: using `typedef` to create an alias will result in a compiler error
```objective-c
typedef SDWebImageManager SDImageManager;
```
```
SDImageManager.h:240:27: Redefinition of 'SDImageManager' as different kind of symbol
```

**Comment by bpoplauschi** [comment]
About my idea above, the one downside is imports file names will also changes, so for those who have explicitly `#import <SDWebImage/SDWebImageManager.h>` it will break. Not sure if many did this.

**Comment by dreampiggy** [comment]
@bpoplauschi That `compatibility_alias` is not magic solution. Especially when you use something like type check, `@class`, `@protocol`, `isKindOfClass:`. They all fail because there are only one `SDImageManager` class in the runtime. It just a typedef. This will cause many potential problems.

![image](https://user-images.githubusercontent.com/6919743/39306047-a0b3664e-4991-11e8-97ab-0646ee9a8fe8.png)

I think, that `manager` is designed as a bridge to cache & downloader. In 5.x we support custom loader protocol. But actually the usage for that loader protocol is about `Custom Network , Third-party Cloud service`. For example, our company using [Cronet](https://chromium.googlesource.com/chromium/src/+/master/components/cronet) instead of `NSURLSession` for most of network request. That `SDWebImageDownloadOperation` is hard to modify because it tied to `NSURLSession` stack.

I guess maybe for most user, that `SDWebImageLoader` protocol is just `SDWebImageDownloader` protocol. So keeping the `Web` make sense...

**Comment by dreampiggy** [comment]
`SDWebImageCacheSerializer`, `SDWebImageCacheKeyFilter` are all created only for `SDWebImageManager`. It's just a wrapper of the original block in manager property, to solve Swift API issue described in #2261. You can check that to know why I have to use this wrapped object instead a simple block.

So I think, since this is tied with manager. We should keep these 3 have the same naming, that `SDCacheKeyFilter` does not make any sense. The function of this is to `provide a mapping between `NSURL` to download and `CacheKey` to store to cache. So it's all about `WebCache` and `URL` loading. Should contains `Web` prefix.

**Comment by dreampiggy** [comment]
`SDWebImageContext` is introduced by #2189 . It's a enhancement for `SDWebImageOptions` to store any object that enum can not hold. It behaves like the arrow in that architecture picture. Which passed from top-level API, to the bottom base module. So `SDWebImageOptions` & `SDWebImageContext` should contains the same naming.

These two is about the SDWebImage framework level configuration, they are not a single class related to image or not. (Contains many config). So I suggest to keep `SDWebImage` prefix to specify that.

**Comment by dreampiggy** [comment]
`SDWebImageTransition` this naming...Well, though I suggest to keep `SDWebImage` prefix because it's only used for View Category. But it should become `SDImageTransition`, because Transition animation is about `UIView`, but not image. 😅 So even you're really strongly to change the name, the name should be `SDTransition` or something

**Comment by rs** [comment]
Won't those name changes make it harder for users to upgrade without a clear benefit?

**Comment by bpoplauschi** [comment]
@rs I don't think there's a clear answer. There are benefits to shortening the entity names and making them more clear (or not, even that is up to debate) and a major release is the place to do so. On the other hand, I get why people might be avoiding the upgrade if it's to much work.
But for the changes we have currently applied, most of them are only 5.x features, so no friction there.
We have agreed not to changed `SDWebImageManager` or `SDWebImageDownloader`.

**Comment by dreampiggy** [comment]
@bpoplauschi And I have a idea in my mind and may related to this naming. See the architecture picture again. Since we now seperate the top-level API between the base module. And base module only dependent on system framework such as `Image/IO`, `Core Image`. And it does not import any header other than `SDWebImageCompat.h`. Maybe we can do this further?

Like [YYImage](https://github.com/ibireme/YYImage) and [YYWebImage](https://github.com/ibireme/YYWebImage), what about put all the image processing/decoding/encoding code, into another framework (CocoaPods Pods) called `SDImage`. We can move all the files like `SDImageCoder`, `SDAnimatedImage/SDAnimatedImageView`, `Image Categories` to that repo. Then the `SDWebImage` framework dependent on this repo.

So the naming issue is need to re-considerate. After that `SD` contains multiple repos, so that `SDWebImageOptions`, `SDWebImageContext`, `SDWebImageError` is valid enough because `SDImage` does not use this `error`, `options`. Naming it without `SDWebImage` prefix will not make it clear :)

**Comment by dreampiggy** [comment]
@bpoplauschi I can create a demo repo represent this. I think seperate the `image` part to another framework is better. And this can also end up the naming discussion because now. `SD` does not only represent Web/Cache. So we may need `SDWebImage` prefix to indicate that this class is only availble for Web/Cache.

See [SDImage's Repo](https://github.com/dreampiggy/SDImage)

**Comment by dreampiggy** [comment]
😅 Any idea about this now ? @mythodeia @skyline75489 

And I wonder if this suitable to move all the image related code into another repo `SDImage` ? Make `SDWebImage` itself depend on that repo ? It's this suitable ? What do you think ( Althrough maybe you're not develop iOS platform application. But this seems a common problem about software architecture)  @rs 

My personal future imagination of SDWebImage can represent like this.

> Out-of-box functionality and fully extensibility.

![- sdwebimage 001](https://user-images.githubusercontent.com/6919743/39393846-ba17893c-4afc-11e8-9202-0d4df244c45e.jpeg)

**Comment by rs** [comment]
I'm not sure to understand the need for multiple repos. Can't you have all the components in the same one? Maintaining multiple repos for libraries that depend on each other can be tedious. Any feature that will span on multiple components will require some gymnastic with multiple commits and dependency conditions.

**Comment by bpoplauschi** [comment]
I agree with @rs on this one. From my pov, all the core functionality from SDWebImage should remain into this project (easier to maintain and easier for the existing users). What I suggested above was to make sure we don't have pieces that do something else than our core lib. For instance, the concrete implementations of the transformers. Or pieces like the Bridges you mentioned in the diagram (that link `SDWebImage` to other modules). But for now, I don't see any obvious ones that could be made a separate project. Another example are the coders (like `APNG` or `ProgressiveJPEG` coders that are not used by a lot of our users and are well definable outside our lib.

**Comment by dreampiggy** [comment]
@bpoplauschi OK...Just a think of this approach. I guess someone may like to use that `SDAnimatedImage` or custom coder as a module without need of `Web-Cache` part in their own lib. But since there are no issue talk about this feature...Maybe we just keep `SDWebImage` single framework.

**Comment by dreampiggy** [comment]
@Baichenghui @mythodeia This discussion seems take so long time. I'd like to give up 😅 
What else some important thing to do before we release 5.0.0-beta...I guess seems we take so long time during 5.x development...If there are no any huge pending issue (Small fix or API break can be adopted between 5.0.0-beta to the final 5.0.0-release), I think maybe we can soon release the beta version. (4.x's latest release 4.3.4 can also be taked)

**Comment by bpoplauschi** [comment]
Ok. Let's close the renaming here. I just want to release a 5.0.0-beta asap.
